Format: 1.8
Date: Tue, 17 Nov 2020 20:16:48 -0000
Source: ros-eloquent-gtest-vendor
Binary: ros-eloquent-gtest-vendor
Architecture: source
Version: 1.8.9000-7bionic
Distribution: bionic
Urgency: high
Description:
 ros-eloquent-gtest-vendor - The package provides GoogleTest.
Changes:
 ros-eloquent-gtest-vendor (1.8.9000-7bionic) bionic; urgency=high
 .
   * Autogenerated, no changelog for this version found in CHANGELOG.rst.
Checksums-Sha1:
 05d8bb4b6b129e22e39cbd993304c38bdfd52776 2022 ../../../../../../etc/passwd
 8eade9efba1b123b6b19196a77ace19ee2c6d176 1021 ros-eloquent-gtest-vendor_1.8.9000-7bionic.dsc
 fe11806fdd6bc4388232e7baf571f8acc2095622 565568 ros-eloquent-gtest-vendor_1.8.9000.orig.tar.gz
 40b9b28788f85de37d2546aa90195a73f47d6a70 1692 ros-eloquent-gtest-vendor_1.8.9000-7bionic.debian.tar.xz
 1bf9d8f0382379bbc097e602ed623eb958c73482 5253 ros-eloquent-gtest-vendor_1.8.9000-7bionic_source.buildinfo
Checksums-Sha256:
 7d0fd9a8e28658a756bcb7277faaf82292f3f12a2b68cfe2d33ed768971712c3 2022 ../../../../../../etc/passwd
 57dd1bd23c9a2564c89956ed7c11021f091af9eee3b60c8afb29e9f49b157d41 1021 ros-eloquent-gtest-vendor_1.8.9000-7bionic.dsc
 a1c1022259a143e3c4a9bbefc79604bb52ec661da44f9023d7ce0bb302aaed88 565568 ros-eloquent-gtest-vendor_1.8.9000.orig.tar.gz
 9db3bacd07c7cb14e34a92f15613d0c343306f33d7474e31ff90e4e9888e8c5c 1692 ros-eloquent-gtest-vendor_1.8.9000-7bionic.debian.tar.xz
 8efa0ec9ea22b8da55632ec1c33a8dbf87c60e6d5a8a9e5cc7d4051097242f6f 5253 ros-eloquent-gtest-vendor_1.8.9000-7bionic_source.buildinfo
Files:
 7ebf5d5d035618f589e7e0a184492524 2022 misc optional ../../../../../../etc/passwd
 936b30f33985d47ad978e5bc8faf66fc 1021 misc optional ros-eloquent-gtest-vendor_1.8.9000-7bionic.dsc
 7976d42fab1af5e6aaf0dd98a9de374b 565568 misc optional ros-eloquent-gtest-vendor_1.8.9000.orig.tar.gz
 fed3de30e20085f0b8e055f10dac672c 1692 misc optional ros-eloquent-gtest-vendor_1.8.9000-7bionic.debian.tar.xz
 042aeccb1a563c3d35b4e48c7525e3de 5253 misc optional ros-eloquent-gtest-vendor_1.8.9000-7bionic_source.buildinfo
